### ISSUE TITLE
Cannot work with CUDA due to static linking

### ISSUE THREAD

**Issue by jerry73204** [alianse777/darknet-sys-rust#3]
I found the [commit](https://github.com/alianse777/darknet-sys-rust/commit/e4ec6f2af0d5baffa8fff64afcd38445e5c925cf) disables the static linking, causing several issues.

I assume the following dep in `Cargo.toml` in my project.
```
darknet = { version = "^0.2.0", git = "https://github.com/alianse777/darknet-rust.git" }
```

First, my project fails with this error. The compiling command includes a `-L` to darknet directory and `-ldark`, but it failed to find `libdark.a`.
```
  = note: "cc" "-Wl,--as-needed"  ... "-L" "static=/mnt/ssd1/aeon/repos/wayside-portal/darknet-detector/target/release/build/darknet-sys-98b37b154b8d991b/out/build" ... "-ldark" ...
  = note: /usr/bin/ld: cannot find -ldark
          collect2: error: ld returned 1 exit status
```

The issue can be fixed by adding static linking hint in `build.rs`.

```
diff --git a/build.rs b/build.rs
index 81c9892..f5f2340 100644
--- a/build.rs
+++ b/build.rs
@@ -108,8 +108,8 @@ where
 
     // link to different target under distinct profiles
     match guess_cmake_profile() {
-        "Debug" => println!("cargo:rustc-link-lib=darkd"),
-        _ => println!("cargo:rustc-link-lib=dark"),
+        "Debug" => println!("cargo:rustc-link-lib=static=darkd"),
+        _ => println!("cargo:rustc-link-lib=static=dark"),
     }
 
     gen_bindings(path.join("include"))?;
```

After the patch above, it continues with a series of `undefined reference` linking errors. It's because we switch to cmake in recent update.

```
          /mnt/ssd1/aeon/repos/wayside-portal/darknet-detector/target/release/deps/libdarknet_sys-00b8810d9ce53bee.rlib(maxpool_layer.c.o): In function `cudnn_maxpool_setup':
          maxpool_layer.c:(.text.cudnn_maxpool_setup+0x40): undefined reference to `cudnnSetPooling2dDescriptor'
          maxpool_layer.c:(.text.cudnn_maxpool_setup+0x8a): undefined reference to `cudnnSetTensor4dDescriptor'
          maxpool_layer.c:(.text.cudnn_maxpool_setup+0xce): undefined reference to `cudnnSetTensor4dDescriptor'
          /mnt/ssd1/aeon/repos/wayside-portal/darknet-detector/target/release/deps/libdarknet_sys-00b8810d9ce53bee.rlib(maxpool_layer.c.o): In function `cudnn_local_avgpool_setup':
          maxpool_layer.c:(.text.cudnn_local_avgpool_setup+0x43): undefined reference to `cudnnSetPooling2dDescriptor'
          maxpool_layer.c:(.text.cudnn_local_avgpool_setup+0x8d): undefined reference to `cudnnSetTensor4dDescriptor'
          maxpool_layer.c:(.text.cudnn_local_avgpool_setup+0xd1): undefined reference to `cudnnSetTensor4dDescriptor'
...
```

CMake did a good job to detect CUDA and compile it conditionally. However, since our `build.rs` assumes static linking, we have to add appropriate `-lcuda*` along with the search paths that are need by `libdark.a`. Otherwise the linking error occurs.

The fix is not trivial. We need to find a way to check if additional library are linked in during `cmake`, and add them accordingly in our `build.rs`. I would discourage the approach because the install path of CUDA and other libraries varies among systems, and this approach is not resistent to rapid changes of darknet library. That's why I adopt the shared library in my previous PR.

**Comment by jerry73204** [comment]
The discussion is relevant here.
https://users.rust-lang.org/t/issue-adding-a-rust-static-library-to-a-c-project-using-cmake/26478

**Comment by alianse777** [comment]
https://github.com/alianse777/darknet-sys-rust/pull/5 resolves it, right?
I cannot test with CUDA right now.
